'use client'

import Link from 'next/link'
import { ArrowLeft, BookOpen, ChevronRight } from 'lucide-react'

const sections = [
  { id: 'gap', title: '1. Gap %', intro: "Gap % measures the difference between today's opening level and the previous close. It is the first signal read each morning and feeds directly into Market Bias.", columns: ['Gap %', 'Reading'], rows: [['>0.75%', 'Strong Gap Up'], ['0.25% – 0.75%', 'Normal Gap Up'], ['-0.25% to 0.25%', 'Flat'], ['-0.75% to -0.25%', 'Normal Gap Down'], ['<-0.75%', 'Strong Gap Down']] },
  { id: 'iv-vix', title: '2. IV vs VIX', intro: "Compare the ATM implied volatility of the specific strike against India VIX to judge whether the premium is fairly priced, rich, or cheap.", columns: ['Condition', 'Reading'], rows: [['Within ±2% of VIX', 'Fairly priced — trade normally'], ['3%+ above VIX', 'Overpriced premium — move closer to ATM or skip'], ['More than 2% below VIX', 'Slightly cheap — mildly favorable, trade per VIX rule']] },
  { id: 'vix', title: '3. VIX Level', intro: 'India VIX sets the overall risk posture for the day: how rich premiums are and which strike to prefer.', columns: ['VIX', 'Guidance', 'Strike'], rows: [['Below 11', 'Trade with caution — small premiums, theta-heavy', 'ATM only on strong momentum'], ['11–14', 'Normal conditions, ideal for buying', 'ATM / ITM by setup'], ['14–18', 'Elevated — premiums are richer', 'Prefer 1-strike ITM'], ['18–22', 'High — IV crush risk', '2-strike ITM only, or skip'], ['Above 22', 'Avoid fresh option buys', 'Wait for VIX to normalize']] },
  { id: 'pcr', title: '4. PCR (Put-Call Ratio)', intro: 'PCR reads options positioning: a high ratio means more puts are written relative to calls, typically a contrarian bullish signal.', columns: ['PCR', 'Reading'], rows: [['> 1.3', 'Oversold / Bullish bias'], ['0.8 – 1.3', 'Neutral'], ['< 0.8', 'Overbought / Bearish bias']] },
  { id: 'max-pain', title: '5. Max Pain', intro: 'Max Pain is the strike at which option writers lose the least at expiry. Price often gravitates toward this level as expiry approaches.', columns: ['Spot vs Max Pain', 'Reading'], rows: [['Above by >0.3%', 'Downward pull likely toward expiry'], ['Within ±0.3%', 'Pinning likely'], ['Below by >0.3%', 'Upward pull likely toward expiry']] },
  { id: 'oi', title: '6. Open Interest Change', intro: 'OI change at key support and resistance strikes is a proxy for whether a level is being defended or abandoned.', columns: ['OI Signal', 'Reading'], rows: [['Support = Addition', 'Support strengthening'], ['Support = Unwinding', 'Support weakening — breakdown risk'], ['Resistance = Addition', 'Resistance strengthening'], ['Resistance = Unwinding', 'Resistance weakening — breakout risk']] },
  { id: 'dte', title: '7. Days to Expiry (DTE)', intro: 'Time to expiry governs gamma risk: how sharply an option can swing on a small move in the underlying.', columns: ['DTE', 'Reading'], rows: [['≤ 1', 'High gamma risk — prefer spreads'], ['2 – 4', 'Normal'], ['> 4', 'Lower gamma risk — naked options viable if conviction is high']] },
  { id: 'event', title: '8. Event Today', intro: 'High-visibility events are tiered by expected market impact. Only High-impact events change the suggested strategy.', columns: ['Impact tier', 'Action'], rows: [['High', 'Display event and time; override to Trade with caution'], ['Medium', 'Informational tag; normal rules apply'], ['Low', 'Informational tag; normal rules apply'], ['None', 'No message shown']] },
  { id: 'strategy', title: '9. Strategy Selection', intro: 'Combine the directional read (Trend vs Range) with IV pricing. DTE and a High-impact event can override the base selection.', columns: ['Condition', 'Strategy'], rows: [['Trend + High IV', 'Debit Spread'], ['Range + High IV', 'Credit Spread'], ['Trend + Low/Fair IV', 'Naked Option'], ['Range + Low/Fair IV', 'Iron Condor'], ['Any + DTE ≤ 1', 'Force Spread / Iron Condor'], ['High-impact Event Today', 'Trade with Caution']] },
]

const formulas = [
  ['Daily expected move', 'Straddle-implied = ATM Straddle Price ÷ √(max(DTE, 1))', 'Historical = 5-Day Average Move. Conservative = smaller estimate; Aggressive = larger estimate.'],
  ['Target / stop-loss', 'Target = Expected Move × 60%', 'Stop-Loss = Expected Move × 30%'],
  ['Strike selection', 'Below 14 → ATM · 14–18 → ITM1 · 18+ → ITM2', 'Effective delta: 0.50 · 0.62 · 0.72'],
  ['Naked option premium', 'Target premium = Target points × Effective Delta', 'Stop-loss premium = Stop points × Effective Delta'],
  ['Spread structure', 'NIFTY hedge width = 200 points · SENSEX = 400 points', 'Debit: max profit = width × lot size − net premium. Credit: max profit = net premium.'],
]

export default function DetailedRulesPage() {
  return <main className="rules-doc-shell"><header className="rules-doc-topbar"><Link href="/" className="back-link"><ArrowLeft size={16} /> Back to dashboard</Link><div className="brand-mark"><div className="brand-symbol"><BookOpen size={16} /></div><div><strong>RULES ENGINE</strong><span>DETAILED REFERENCE</span></div></div></header><div className="rules-doc-layout"><aside className="rules-doc-nav"><p className="eyebrow">On this page</p>{sections.map((section) => <a key={section.id} href={`#${section.id}`}>{section.title.replace(/^\d+\. /, '')}<ChevronRight size={13} /></a>)}<a href="#methodology">Expected move & targets<ChevronRight size={13} /></a></aside><article className="rules-doc-content"><div className="doc-hero"><p className="eyebrow">Rules Engine — Detailed Reference</p><h1>How signals become decisions</h1><p>Full methodology behind the NIFTY/SENSEX premarket signals: how each input is read, how bias and strategy are derived, and how targets and stop-losses are calculated.</p></div>{sections.map((section) => <section className="doc-section" id={section.id} key={section.id}><h2>{section.title}</h2><p className="doc-intro">{section.intro}</p><div className="doc-table"><div className="doc-table-head">{section.columns.map((column) => <span key={column}>{column}</span>)}</div>{section.rows.map((row) => <div className="doc-table-row" key={row.join('-')}>{row.map((cell) => <span key={cell}>{cell}</span>)}</div>)}</div></section>)}<section className="doc-section" id="methodology"><h2>10. Expected Move & Target / Stop-Loss</h2><p className="doc-intro">Convert volatility inputs into a concrete points target, stop-loss, and premium target for naked options and spreads. Lot size and net premium remain trader-entered values.</p><div className="formula-grid">{formulas.map(([title, formula, note]) => <article className="formula-card" key={title}><p className="eyebrow">{title}</p><strong>{formula}</strong><span>{note}</span></article>)}</div></section><div className="doc-note"><strong>Methodology note</strong><span>Trend vs Range is currently an input based on judgment; a formal source rule is planned but not finalized.</span></div></article></div></main>
}
