import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowLeft, BookOpen, ChevronRight } from 'lucide-react'
import { FaqBlock } from '@/components/faq-block'
import { SEED_FAQ, faqJsonLd } from '@/lib/faq'

const SITE_URL = 'https://marketcue.in'

export const metadata: Metadata = {
  title: 'How MarketCue scores Nifty and Sensex — the full rules',
  description:
    'The exact weighted scoring rules behind every MarketCue read: gap, OI, PCR, max pain, IV and India VIX inputs, and how they resolve to bias and option readiness.',
  alternates: { canonical: `${SITE_URL}/rules` },
}

// This documentation was rewritten to match the framework actually implemented in computeMarketBias /
// computeOptionReadiness / computeStrategyRecommendation (app/page.tsx). It replaces the old Trend-vs-Range
// bias vote (which included advance/decline ratio), the fixed ±2-point IV/VIX threshold, the flat 60%/30%
// target/stop formula, and the DTE≤1 / high-impact-event strategy overrides — none of which reflect live logic.
const sections = [
  { id: 'gap', title: '1. Market Bias — Gap %', intro: "Gap % measures the difference between today's opening level and the previous close. It is one of four weighted inputs to the Stage 1 Market Bias score, contributing 45% of the total when DTE is greater than 3 days and 25% when DTE is 3 days or fewer.", columns: ['Gap %', 'Reading', 'Score'], rows: [['> 0.75%', 'Strong Gap Up', '+2'], ['0.25% – 0.75%', 'Normal Gap Up', '+1'], ['-0.25% to 0.25%', 'Flat', '0'], ['-0.75% to -0.25%', 'Normal Gap Down', '-1'], ['<-0.75%', 'Strong Gap Down', '-2']] },
  { id: 'oi', title: '2. Market Bias — Open Interest Structure', intro: 'OI change at key support and resistance strikes is a proxy for whether a level is being defended or abandoned. The support component and the resistance component are each scored, then summed and clamped to a range of -2 to +2. This combined OI score contributes 25% of Market Bias when DTE is greater than 3 days and 45% when DTE is 3 days or fewer — the single largest weight of any input close to expiry.', columns: ['OI Signal', 'Reading', 'Component score'], rows: [['Support: Addition', 'Support strengthening', '+1'], ['Support: Unwinding', 'Support weakening — breakdown risk', '-1'], ['Resistance: Addition', 'Resistance strengthening', '-1'], ['Resistance: Unwinding', 'Resistance weakening — breakout risk', '+1']] },
  { id: 'pcr', title: '3. Market Bias — PCR (Put-Call Ratio)', intro: 'PCR reads options positioning: a high ratio means more puts are written relative to calls, typically a contrarian bullish signal. It contributes a fixed 20% of Market Bias regardless of DTE.', columns: ['PCR', 'Reading', 'Score'], rows: [['> 1.30', 'Oversold / Bullish bias', '+2'], ['0.80 – 1.30', 'Neutral', '0'], ['< 0.80', 'Overbought / Bearish bias', '-2']] },
  { id: 'max-pain', title: '4. Market Bias — Max Pain', intro: 'Max Pain is the strike at which option writers lose the least at expiry. Price often gravitates toward this level as expiry approaches. It contributes a fixed 10% of Market Bias regardless of DTE.', columns: ['Spot vs Max Pain', 'Reading', 'Score'], rows: [['Below by >0.3%', 'Upward pull likely toward expiry', '+1'], ['Within ±0.3%', 'Pinning likely', '0'], ['Above by >0.3%', 'Downward pull likely toward expiry', '-1']] },
  { id: 'bias-weights', title: '5. Market Bias — Weights by DTE', intro: 'Each of the four signals above is weighted differently depending on how many days remain to expiry. Closer to expiry, Open Interest structure becomes the dominant signal and Gap % is discounted; further from expiry, the reverse is true.', columns: ['Days to expiry', 'Weights'], rows: [['> 3 days', 'Gap 45% · OI 25% · PCR 20% · Max Pain 10%'], ['≤ 3 days', 'Gap 25% · OI 45% · PCR 20% · Max Pain 10%']] },
  { id: 'bias-bands', title: '6. Market Bias — Final Bands', intro: 'The four component scores are multiplied by their DTE-appropriate weights and summed into a single Market Bias score, then mapped to one of five bands.', columns: ['Bias score', 'Label'], rows: [['+1.25 to +2.00', 'Strong Bullish'], ['+0.50 to +1.24', 'Bullish'], ['-0.49 to +0.49', 'Neutral'], ['-0.50 to -1.24', 'Bearish'], ['-1.25 to -2.00', 'Strong Bearish']] },
  { id: 'vix', title: '7. Option Readiness — VIX Score', intro: 'India VIX sets the overall risk posture for the day. It is the first of three inputs summed into the Stage 2 Option Readiness score.', columns: ['India VIX', 'Reading', 'Score'], rows: [['11 – 14', 'Ideal, low-risk premium', '+2'], ['Below 11', 'Thin, theta-heavy premium', '+1'], ['14 – 18', 'Elevated premium', '0'], ['18 – 22', 'High — IV crush risk', '-1'], ['Above 22', 'Blocks fresh option buying only — selling strategies stay allowed', '-2']] },
  { id: 'iv-vix', title: '8. Option Readiness — IV vs VIX', intro: 'Compare the ATM implied volatility against India VIX, using a proportional band around VIX rather than a fixed point gap, to judge whether the premium is cheap, fairly priced, or expensive.', columns: ['Condition', 'Reading', 'Score'], rows: [['IV < VIX × 0.9', 'Cheap', '+2'], ['IV ≤ VIX × 1.1', 'Normal', '+1'], ['IV > VIX × 1.1', 'Expensive', '-1']] },
  { id: 'dte-readiness', title: '9. Option Readiness — DTE Score', intro: 'Time to expiry governs gamma risk and is the third input to Option Readiness. Note this DTE score is separate from — and does not override — the Stage 3 strategy pick; it only feeds the readiness total below.', columns: ['DTE', 'Reading', 'Score'], rows: [['2 – 4', 'Ideal window', '+2'], ['> 4', 'Lower gamma risk', '+1'], ['≤ 1', 'High gamma risk', '-1']] },
  { id: 'readiness-bands', title: '10. Option Readiness — Final Bands', intro: 'The VIX, IV-vs-VIX, and DTE scores are summed (range -4 to +6) into a single Option Readiness score. An Avoid reading forces No Trade for Stage 3 regardless of what Market Bias says.', columns: ['Readiness score', 'Label'], rows: [['+4 to +6', 'Good to Buy'], ['+1 to +3', 'Caution'], ['≤ 0', 'Avoid']] },
  { id: 'strategy', title: '11. Strategy Recommendation', intro: 'Stage 3 matches the Market Bias band against the Option Readiness IV Condition, VIX, and DTE to pick a strategy. VIX above 22 blocks fresh premium-buying strategies only — credit/selling strategies stay allowed. A DTE of 1 or fewer downgrades Naked Call/Put to the matching Debit Spread rather than blocking the trade outright. Each "No Trade" outcome carries its own specific reason (for example, cheap IV with no edge to sell versus fairly priced IV with no directional edge) rather than one generic message.', columns: ['Condition', 'Recommendation'], rows: [['Bullish + Cheap IV + Good to Buy (normal VIX)', 'Naked Call (→ Call Debit Spread if DTE ≤ 1)'], ['Bullish + Cheap/Normal IV', 'Call Debit Spread'], ['Bullish + Expensive IV, or high VIX', 'Put Credit Spread'], ['Bearish + Cheap IV + Good to Buy (normal VIX)', 'Naked Put (→ Put Debit Spread if DTE ≤ 1)'], ['Bearish + Cheap/Normal IV', 'Put Debit Spread'], ['Bearish + Expensive IV, or high VIX', 'Call Credit Spread'], ['Neutral + Cheap IV', 'No Trade / Wait'], ['Neutral + Normal IV', 'No Trade / Wait'], ['Neutral + Expensive IV', 'Iron Condor'], ['Neutral + High VIX', 'Iron Condor']] },
]

const formulas = [
  ['GIFT Nifty predicted open', 'Predicted (points) = GIFT Nifty gap % ÷ 100 × NIFTY previous close', 'Difference = actual opening gap (points) − predicted. SENSEX has no equivalent leading indicator.'],
  ['Expected move (Conservative / Aggressive)', 'Option-implied = ATM Straddle Price ÷ √(max(DTE, 1))', 'Historical = 5-day average daily range (High − Low). Conservative = the smaller of the two estimates; Aggressive = the larger.'],
  ['Target / stop-loss — buyer strategies', 'Naked Call/Put, Debit Spread: Target/Stop = Expected Move (points) × the strike\u2019s effective delta', 'Net premium plays no role here — identical regardless of what premium was actually paid.'],
  ['Target / stop-loss — seller strategies', 'Credit Spread, Iron Condor: Conservative Target = Net Premium × 60%, Conservative Stop = Net Premium × 40%', 'Aggressive Target = Net Premium × 75%, Aggressive Stop = Net Premium × 25%.'],
  ['Book profit / book stop — buyer strategies', 'Book Profit = Target (points) × Qty × 60%', 'Book Stop = Stop (points) × Qty × 40%'],
  ['Book profit / book stop — seller strategies', 'Book Profit = Target × Qty', 'Book Stop = Stop × Qty — no extra split, since the 60/40–75/25 split already happened at the Target/Stop-loss level.'],
]

export default function DetailedRulesPage() {
  return <><script
    type="application/ld+json"
    // eslint-disable-next-line react/no-danger
    dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd(SEED_FAQ)) }}
  /><main className="rules-doc-shell"><header className="rules-doc-topbar"><Link href="/dashboard" className="back-link"><ArrowLeft size={16} /> Back to dashboard</Link><div className="brand-mark"><div className="brand-symbol"><BookOpen size={16} /></div><div><strong>RULES ENGINE</strong><span>DETAILED REFERENCE</span></div></div></header><div className="rules-doc-layout"><aside className="rules-doc-nav"><p className="eyebrow">On this page</p>{sections.map((section) => <a key={section.id} href={`#${section.id}`}>{section.title.replace(/^\d+\. /, '')}<ChevronRight size={13} /></a>)}<a href="#methodology">Predicted open &amp; targets<ChevronRight size={13} /></a></aside><article className="rules-doc-content"><div className="doc-hero"><p className="eyebrow">Rules Engine — Detailed Reference</p><h1>The MarketCue rules engine</h1><p>Full methodology behind the NIFTY/SENSEX premarket signals: the weighted Market Bias score, the combined Option Readiness score, the Bias/IV/VIX/DTE strategy lookup, and how predicted open, expected move, targets, and stop-losses are calculated.</p><p className="doc-hero-links">See it applied on the <Link href="/">MarketCue homepage</Link> or in the daily <Link href="/nifty-sensex-today">Nifty &amp; Sensex Today</Link> reads.</p></div>{sections.map((section) => <section className="doc-section" id={section.id} key={section.id}><h2>{section.title}</h2><p className="doc-intro">{section.intro}</p><div className="doc-table"><div className="doc-table-head">{section.columns.map((column) => <span key={column}>{column}</span>)}</div>{section.rows.map((row) => <div className="doc-table-row" key={row.join('-')}>{row.map((cell) => <span key={cell}>{cell}</span>)}</div>)}</div></section>)}<section className="doc-section" id="methodology"><h2>12. Predicted Open, Expected Move &amp; Targets</h2><p className="doc-intro">Convert volatility inputs into a concrete points target, stop-loss, and book profit/stop for buyer and seller strategies alike. Lot size and net premium remain trader-entered values.</p><div className="formula-grid">{formulas.map(([title, formula, note]) => <article className="formula-card" key={title}><p className="eyebrow">{title}</p><strong>{formula}</strong><span>{note}</span></article>)}</div></section><div className="doc-note"><strong>Methodology note</strong><span>Market Bias, Option Readiness, and Strategy Recommendation are fully rule-based — there is no discretionary Trend-vs-Range judgment call. VIX above 22 only blocks fresh option buying; selling strategies remain available at any VIX level, and a DTE of 1 or fewer only downgrades naked options to the matching debit spread rather than forcing a spread or Iron Condor across the board.</span></div><FaqBlock items={SEED_FAQ} /></article></div></main></>
}
