'use client'

import { useEffect, useMemo, useState } from 'react'
import { Activity, AlertTriangle, BarChart3, BookOpen, CheckCircle2, ChevronRight, Clock3, Gauge, Layers3, Menu, Moon, RefreshCw, ShieldAlert, Sun } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'

type Row = Record<string, string | number | null>
type Phase = 'premarket' | 'open' | 'mid' | 'post'
const phases = [
  { id: 'premarket' as Phase, label: 'Pre-market', subtitle: 'Overnight setup', icon: Clock3 },
  { id: 'open' as Phase, label: 'Market open', subtitle: 'Opening auction', icon: Activity },
  { id: 'mid' as Phase, label: 'Mid-market', subtitle: 'Intraday read', icon: Gauge },
  { id: 'post' as Phase, label: 'Post-market', subtitle: 'Review & learn', icon: Layers3 },
]
const phaseFields: Record<Phase, { label: string; key: string; pct?: boolean }[]> = {
  premarket: [
    ['India VIX', 'india_vix'], ['VIX change', 'india_vix_change_pct', true], ['GIFT Nifty gap', 'gift_nifty_gap_pct', true], ['Nifty expiry', 'days_to_expiry_nifty'], ['Sensex expiry', 'days_to_expiry_sensex'], ['Nifty 5D average move', 'avg_move_5d_nifty'], ['Sensex 5D average move', 'avg_move_5d_sensex'], ['Nifty prior day', 'prev_day_change_pct_nifty', true], ['Sensex prior day', 'prev_day_change_pct_sensex', true], ['Nifty chart support', 'chart_support_nifty'], ['Nifty chart resistance', 'chart_resistance_nifty'], ['Sensex chart support', 'chart_support_sensex'], ['Sensex chart resistance', 'chart_resistance_sensex'], ['Nifty OI support', 'oi_support_nifty'], ['Nifty OI resistance', 'oi_resistance_nifty'], ['Sensex OI support', 'oi_support_sensex'], ['Sensex OI resistance', 'oi_resistance_sensex'], ['Support OI action', 'oi_change_support_nifty'], ['Resistance OI action', 'oi_change_resistance_nifty'],
  ].map(([label, key, pct]) => ({ label, key, pct: Boolean(pct) })),
  open: [
    ['Nifty opening points', 'nifty_opening_points'], ['Advance / decline', 'advance_decline_ratio'], ['Nifty previous close', 'prev_close_nifty'], ['Sensex previous close', 'prev_close_sensex'], ['Nifty gap points', 'gap_points_nifty'], ['Sensex gap points', 'gap_points_sensex'], ['Nifty ATM IV', 'atm_iv_nifty', true], ['Sensex ATM IV', 'atm_iv_sensex', true], ['Nifty ATM straddle', 'atm_straddle_price_nifty'], ['Sensex ATM straddle', 'atm_straddle_price_sensex'], ['Nifty straddle delta', 'atm_straddle_delta_nifty'], ['Sensex straddle delta', 'atm_straddle_delta_sensex'], ['Nifty straddle theta', 'atm_straddle_theta_nifty'], ['Sensex straddle theta', 'atm_straddle_theta_sensex'], ['Nifty PCR', 'pcr_nifty'], ['Sensex PCR', 'pcr_sensex'], ['Nifty max pain', 'max_pain_nifty'], ['Sensex max pain', 'max_pain_sensex'],
  ].map(([label, key, pct]) => ({ label, key, pct: Boolean(pct) })),
  mid: [
    ['Mid-market status', 'mid_market_status'], ['Nifty intraday change', 'mid_nifty_change_pct', true], ['Sensex intraday change', 'mid_sensex_change_pct', true], ['Mid-market breadth', 'mid_advance_decline_ratio'], ['Mid-market PCR', 'mid_pcr_nifty'], ['Mid-market VIX', 'mid_india_vix'], ['Mid-market note', 'mid_market_notes'],
  ].map(([label, key, pct]) => ({ label, key, pct: Boolean(pct) })),
  post: [
    ['Post-market status', 'post_market_status'], ['Nifty close', 'post_close_nifty'], ['Sensex close', 'post_close_sensex'], ['Nifty closing change', 'post_change_pct_nifty', true], ['Sensex closing change', 'post_change_pct_sensex', true], ['Final breadth', 'post_advance_decline_ratio'], ['Post-market note', 'post_market_notes'], 
  ].map(([label, key, pct]) => ({ label, key, pct: Boolean(pct) })),
}
function value(row: Row | null, key: string, pct = false) { const v = row?.[key]; if (v === null || v === undefined || v === '') return '—'; return `${pct && Number(v) > 0 ? '+' : ''}${v}${pct ? '%' : ''}` }
function tone(row: Row | null, key: string) { const n = Number(row?.[key]); return Number.isNaN(n) || n === 0 ? '' : n > 0 ? 'positive' : 'negative' }
function PhaseView({ phase, row }: { phase: Phase; row: Row | null }) {
  const fields = phaseFields[phase]; const available = fields.filter((f) => row?.[f.key] != null && row?.[f.key] !== '').length
  const intros: Record<Phase, [string, string]> = { premarket: ['Build a market thesis before the bell', 'Use volatility, overnight pricing and positioning to define scenarios and invalidation levels.'], open: ['Read the opening auction, not just the gap', 'Opening breadth, implied volatility and the straddle tell you whether price discovery is orderly or unstable.'], mid: ['Track whether the opening thesis is holding', 'Compare intraday breadth, volatility and price with the morning hypothesis. Missing values mean the external source has not supplied this phase.'], post: ['Close the loop on the session', 'Turn the day into a repeatable review: what worked, what failed and what to carry forward.'] }
  return <section className="phase-view"><div className="phase-intro"><div><p className="eyebrow">{available} of {fields.length} fields available</p><h2>{intros[phase][0]}</h2><p>{intros[phase][1]}</p></div><div className="coverage"><b>{Math.round(available / fields.length * 100)}%</b><span>source coverage</span></div></div><div className="interpretation"><BookOpen size={18} /><div><strong>How to interpret this phase</strong><p>{phase === 'premarket' ? 'A rising VIX with a negative overnight gap argues for wider ranges. OI additions at support or resistance help define where price may stall.' : phase === 'open' ? 'A gap matters when breadth confirms it. Read PCR and ATM IV together; price up with weak breadth is a fragile signal.' : phase === 'mid' ? 'Look for confirmation or divergence from the morning thesis. Treat unavailable fields as unavailable, not as zero.' : 'Separate process from outcome. Record the close and breadth before evaluating the trade idea.'}</p></div></div><div className="field-grid">{fields.map((f) => <div className={`field-card ${row?.[f.key] == null ? 'is-empty' : ''}`} key={f.key}><span>{f.label}</span><strong className={tone(row, f.key)}>{value(row, f.key, f.pct)}</strong></div>)}</div></section>
}
export default function Dashboard() {
  const [phase, setPhase] = useState<Phase>('premarket'); const [rows, setRows] = useState<Row[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [dark, setDark] = useState(false); const [navOpen, setNavOpen] = useState(true); const supabase = useMemo(() => createClient(), []); const row = rows[0] ?? null
  useEffect(() => { document.documentElement.classList.toggle('dark', dark) }, [dark])
  useEffect(() => { let active = true; (async () => { setLoading(true); const result = await supabase.from('premarket_dashboard').select('*').order('trade_date', { ascending: false }); if (!active) return; if (result.error) setError(result.error.message); else setRows((result.data ?? []) as Row[]); setLoading(false) })(); return () => { active = false } }, [supabase])
  return <main className="app-shell"><header className="topbar"><button className="icon-button mobile-menu" onClick={() => setNavOpen(!navOpen)} aria-label="Toggle navigation"><Menu size={18} /></button><div className="brand-mark"><div className="brand-symbol"><BarChart3 size={16} /></div><div><strong>MARKETVIEW</strong><span>TRADE ANALYSIS PLATFORM</span></div></div><div className="topbar-meta"><span className="live-dot" /> MARKET SESSION <button className="icon-button" onClick={() => setDark(!dark)} aria-label="Toggle theme">{dark ? <Sun size={16} /> : <Moon size={16} />}</button></div></header><div className="workspace"><aside className={`sidebar ${navOpen ? '' : 'closed'}`}><div className="side-label">SESSION MAP</div>{phases.map(({ id, label, subtitle, icon: Icon }) => <button key={id} className={`phase-nav ${phase === id ? 'active' : ''}`} onClick={() => setPhase(id)}><Icon size={17} /><span><strong>{label}</strong><small>{subtitle}</small></span><ChevronRight size={14} /></button>)}<div className="side-rule" /></aside><div className="content"><div className="content-head"><div><p className="eyebrow">{row?.trade_date ?? 'No current row'} · {row?.day_name ?? 'Session date'}</p><h1>{phases.find((p) => p.id === phase)?.label}</h1></div><div className="head-actions"><button className="action-button" onClick={() => location.reload()}><RefreshCw size={15} /> Refresh</button></div></div>{loading ? <div className="state-card"><RefreshCw className="spin" size={20} /> Loading external market data…</div> : error ? <div className="state-card error"><AlertTriangle size={20} />{error}</div> : !row ? <div className="state-card"><ShieldAlert size={20} /> No rows returned from public.premarket_dashboard.</div> : <PhaseView phase={phase} row={row} />}<footer className="data-footer"><span><CheckCircle2 size={14} /> Supabase · SELECT only</span><span>Latest available: {row?.trade_date ?? '—'}</span><span>Event: {row?.event_today ?? '—'}</span></footer></div></div></main>
}
