export type FaqItem = { question: string; answer: string }

// Shared between /rules and /nifty-sensex-today so the visible Q&A text and
// the FAQPage JSON-LD on both pages can never drift out of sync with each
// other -- Google requires the two to match.
export const SEED_FAQ: FaqItem[] = [
  {
    question: 'What is a good PCR for Nifty?',
    answer:
      'A Put-Call Ratio above 1.30 reads as oversold / bullish (more puts written than calls), 0.80–1.30 is neutral, and below 0.80 reads as overbought / bearish. MarketCue weights PCR as a fixed 20% of its Market Bias score regardless of days to expiry.',
  },
  {
    question: 'What does max pain mean in options?',
    answer:
      'Max Pain is the strike price at which option writers as a group would lose the least money at expiry. Price often gravitates toward this level as expiry approaches, so MarketCue reads the distance between spot and Max Pain as a directional pull: more than 0.3% below Max Pain suggests an upward pull, within ±0.3% suggests pinning, and more than 0.3% above suggests a downward pull.',
  },
  {
    question: 'How does India VIX affect option buying?',
    answer:
      'India VIX sets the day’s risk posture. MarketCue reads 11–14 as the ideal, lowest-risk range for buying premium; below 11 as thin, theta-heavy premium; 14–18 as elevated; 18–22 as high with IV-crush risk; and above 22 as a level that blocks fresh option-buying strategies specifically, while selling strategies (credit spreads, iron condors) remain allowed.',
  },
  {
    question: 'What is option readiness?',
    answer:
      'Option Readiness is MarketCue’s Stage 2 score, summing the India VIX score, the IV-vs-VIX score, and the Days-to-Expiry score into a single number from -4 to +6. That total maps to Good to Buy, Caution, or Avoid — telling you whether today’s volatility conditions favor buying options at all, independent of which direction Market Bias points.',
  },
  {
    question: 'How often does MarketCue update its read?',
    answer:
      'MarketCue publishes a pre-market read before the open and a post-market read after the close, every trading day — both generated by the same documented rules engine, not a discretionary call.',
  },
]

// Shared between the live /global-cues-today page and each archived /global-cues-today/[date]
// page, same reasoning as SEED_FAQ above: the visible text and the FAQPage JSON-LD must match.
export const GLOBAL_CUES_FAQ: FaqItem[] = [
  {
    question: 'What is the GIFT Nifty gap?',
    answer:
      'GIFT Nifty is Nifty 50 futures traded in Gujarat, hours before India’s exchanges open. Its move relative to Nifty’s prior close is read as the market’s implied opening gap.',
  },
  {
    question: 'What do FII and DII flows mean?',
    answer:
      'FII (foreign institutional investors) and DII (domestic institutional investors) net cash flows show whether foreign or domestic money was buying or selling Indian equities that session.',
  },
  {
    question: 'What does "transmission" mean on this page?',
    answer:
      'How strongly a global move is actually reaching Indian markets that day, measured against the 20-session historical correlation between Nifty’s daily move and the prior US session.',
  },
  {
    question: 'How is the Global and India read calculated?',
    answer:
      'A deterministic engine scores about 25 free market instruments (US and Asian indices, crude, gold, yields, the dollar) plus India’s own breadth, options positioning and institutional flows. A language model only writes the plain-English explanation of those scores, and every sentence is checked against the underlying figures before it publishes.',
  },
  {
    question: 'How often does this page update?',
    answer:
      'Roughly every 15 minutes while Indian markets are open, and hourly otherwise. The explanation itself is only rewritten when the picture actually changes.',
  },
]

export function faqJsonLd(items: FaqItem[]) {
  return {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: items.map((item) => ({
      '@type': 'Question',
      name: item.question,
      acceptedAnswer: { '@type': 'Answer', text: item.answer },
    })),
  }
}
